# mysite/settings.py
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Import built-in libraries
import os
from pathlib import Path

# Import third-party libraries
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(dotenv_path=BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = os.environ.get("SECRET_KEY", default="your-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG: bool = bool(os.environ.get("DEBUG", default="False"))


# SECURITY WARNING: define the correct hosts in production!
ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS: list[str] = os.environ.get("ALLOWED_HOSTS", default="").split(sep=",")

# Application definition

INSTALLED_APPS: list[str] = [
    "blog.apps.BlogConfig",
    "users.apps.UsersConfig",
    "crispy_forms",
    "crispy_bootstrap4",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Middleware
MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# URL configuration
ROOT_URLCONF = "mysite.urls"

# Template configuration
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI configuration
WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv(key="DB_NAME"),
        "USER": os.getenv(key="DB_USER"),
        "PASSWORD": os.getenv(key="DB_PASSWORD"),
        "HOST": os.getenv(key="DB_HOST", default="localhost"),
        "PORT": os.getenv(key="DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, str]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT: Path = (
    BASE_DIR / "staticfiles"
)  # All necessary static files are collected (python manage.py collectstatic) for deployment.

STATIC_URL = "static/"  # Static files for each root app

STATICFILES_DIRS: list[Path] = [
    BASE_DIR / "globalstaticfiles"
]  # Globally available static files for all apps in the project.

# Media files (user uploaded files)
MEDIA_ROOT: Path = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

LOGIN_REDIRECT_URL = "blog-home"

LOGIN_URL = "login"

# Email configuration for password reset
EMAIL_BACKEND: str | None = os.environ.get("EMAIL_BACKEND")
EMAIL_HOST: str | None = os.environ.get("EMAIL_HOST")
EMAIL_PORT: str | None = os.environ.get("EMAIL_PORT")
EMAIL_USE_TLS: str | None = os.environ.get("EMAIL_USE_TLS")
EMAIL_HOST_USER: str | None = os.environ.get("EMAIL_USER")
EMAIL_HOST_PASSWORD: str | None = os.environ.get("EMAIL_PASS")
DEFAULT_FROM_EMAIL: str | None = os.environ.get("EMAIL_USER")
